server:
  port: 9999
#配置数据库
spring:
  datasource:
    jdbc:
      drive: com.mysql.cj.jdbc.Driver
    username: root
    password: qaz123456
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
mybatis:
  # 配置mapper xml文件路径
  mapper-locations: classpath:mapping/**//*.xml
  #配置映射类所在包名
  type-aliases-package: com.zql.model
  configuration:
  #映射驼峰命名
    map-underscore-to-camel-case: false
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSqle